inputs:

  agent_user_primary_group:
    type: string
    default: 'wheel' # change this other distros

node_templates:

  host_requirements:
    type: cloudify.nodes.CloudInit.CloudConfig
    properties:
      resource_config:
        package_upgrade: true
        users:
          - name: { get_input: agent_user }
            primary-group: { get_input: agent_user_primary_group }
            shell: /bin/bash
            sudo: ['ALL=(ALL) NOPASSWD:ALL']
            ssh-authorized-keys:
              - { get_secret: agent_key_public }
        packages:
        - [epel-release]
        - [python-wheel]
        - [python-pip]
        - [python-setuptools]
        - [gcc]
        - [python-devel] # apt python-dev
        - [libffi-devel] # apt libffi-dev
        - [openssl-devel] # apt openssl-dev
        - [libxml2] # apt libffi-dev
        - [libxslt]
